---
- name: "Docker Installation"
  hosts: centos
  become: yes 
  vars:
    packages:
      - 'docker'
      - 'vim'
    service:
     - 'docker'
  tasks:
    - name: "installation on Docker"
      yum:
        name: "{{ packages }}"
        state: present
    - name: "start and enable"
      service:
        name: "{{ item }}"
        state: "started"
        enabled: true
      loop: '{{service}}'
    - name: "User add"
      user:
        name: ec2-user
        groups: docker
        append: yes


