---
- name: "Web Configuration"
  hosts: centos
  become: true
  tasks:
    - name: "Package Installation"
      yum:
        name:
        - 'httpd'
        - 'php-fpm'    
        state: present
    - name: "service Restart"
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: ['httpd','php-fpm']
    - name: "Copying files"
      copy:
        src: './web/'
        dest: '/var/www/html/'
        owner: 'apache'
        group: 'apache'

